### ISSUE TITLE
NY precincts don't have their names standardized

### ISSUE THREAD

**Issue by arashmahdian** [MEDSL/replication-scripts#3]
At least 70 precinct names need to be standardized.

e.g. 

"CITY OF ITHACA 4 - 1" vs "CITY OF ITHACA 4-1"
"N GREENBUSH 1" vs "NORTH GREENBUSH 1"
"NEW HARTFORD 1-1" vs  "NH WARD 1-1"
"OGDEN 1" vs "ODGEN 1"
"UNSCANNED BALLOTS" vs "UNSCANNED"
"TOWN OF COLUMBIA 1 LD 7" vs "TOWN OF COLUMBIA 1"

**Comment by sbaltzmit** [comment]
per https://github.com/MEDSL/replication-scripts/issues/4#issuecomment-1675982107
